# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
release_dynamic_flag :=
release_static_flag := -static
debug_dynamic_flag :=
debug_static_flag := -static
debug_compilation_flag := -g
debug_link_flag :=
shared_flag := -shared -fPIC
compile_only_flag := -c
link_flag :=
pkg_config_syntax :=
obj_ext := .o
out_ext :=
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	release_dynamic_flag := /MD
	release_static_flag := /MT
	debug_dynamic_flag := /MDd
	debug_static_flag := /MTd
	debug_compilation_flag := /Zi
	debug_link_flag := /DEBUG
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .exe
endif

active_dynamic_flag := $(release_dynamic_flag)
active_static_flag := $(release_static_flag)
active_debug_compilation_flag :=
active_debug_link_flag :=
ifeq ($(MODE),debug)
	active_debug_compilation_flag := $(debug_compilation_flag)
	active_debug_link_flag := $(debug_link_flag)
	active_dynamic_flag := $(debug_dynamic_flag)
	active_static_flag := $(debug_static_flag)
endif

c_compiler := "$(CC)"
cpp_compiler := "$(CXX)"
c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
cpp_compilation_flags := -Wall -Wextra -Wpedantic -std=c++23 -pthread $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
link_time_flags := $(LDFLAGS) $(active_debug_link_flag)
libraries := $(library_flag)"ssl" $(library_flag)"crypto"

ifeq ($(OS),Windows_NT)
	c_compiler := "$(CC)"
	cpp_compiler := "$(CXX)"
	c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	cpp_compilation_flags := /W4 /std:c++latest /EHsc $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	link_time_flags := $(LDFLAGS)
	libraries := $(library_flag)"libssl.lib" $(library_flag)"libcrypto.lib" $(library_flag)"ws2_32.lib"
endif

ifeq ($(TSAN),1)
	c_compiler := "$(CC)"
	cpp_compiler := "$(CXX)"
	c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	cpp_compilation_flags := -Wall -Wextra -Wpedantic -std=c++23 -pthread -fsanitize=thread -fno-omit-frame-pointer $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	link_time_flags := -fsanitize=thread
	libraries := $(library_flag)"ssl" $(library_flag)"crypto"
endif

ifeq ($(ASAN),1)
	c_compiler := "$(CC)"
	cpp_compiler := "$(CXX)"
	c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	cpp_compilation_flags := -Wall -Wextra -Wpedantic -std=c++23 -pthread -fsanitize=address,undefined -fno-omit-frame-pointer $(active_debug_compilation_flag) $(include_path_flag).. $(include_path_flag)../Polynet $(active_dynamic_flag)
	link_time_flags := -fsanitize=address,undefined
	libraries := $(library_flag)"ssl" $(library_flag)"crypto"
endif

all: polyweb-tests$(out_ext)
.PHONY: all

obj/http_0$(obj_ext): ./http.cpp .polybuild.mk ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp ./support.hpp ./test.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/main_0$(obj_ext): ./main.cpp .polybuild.mk ./test.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/tls_0$(obj_ext): ./tls.cpp .polybuild.mk ../Polynet/secure_sockets.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ./test.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/transport_0$(obj_ext): ./transport.cpp .polybuild.mk ./support.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ./test.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/websocket_0$(obj_ext): ./websocket.cpp .polybuild.mk ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp ./support.hpp ./test.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/client_0$(obj_ext): ../client.cpp .polybuild.mk ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/error_0$(obj_ext): ../error.cpp .polybuild.mk ../error.hpp ../Polynet/error.hpp ../Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polyweb_0$(obj_ext): ../polyweb.cpp .polybuild.mk ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/server_0$(obj_ext): ../server.cpp .polybuild.mk ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/string_0$(obj_ext): ../string.cpp .polybuild.mk ../string.hpp ../Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/websocket_1$(obj_ext): ../websocket.cpp .polybuild.mk ../binary.hpp ../polyweb.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp ../Polynet/secure_sockets.hpp ../error.hpp ../thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/error_1$(obj_ext): ../Polynet/error.cpp .polybuild.mk ../Polynet/error.hpp ../Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polynet_0$(obj_ext): ../Polynet/polynet.cpp .polybuild.mk ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/secure_sockets_0$(obj_ext): ../Polynet/secure_sockets.cpp .polybuild.mk ../Polynet/secure_sockets.hpp ../Polynet/polynet.hpp ../Polynet/error.hpp ../Polynet/string.hpp ../string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  obj/http_0$(obj_ext) obj/main_0$(obj_ext) obj/tls_0$(obj_ext) obj/transport_0$(obj_ext) obj/websocket_0$(obj_ext) obj/client_0$(obj_ext) obj/error_0$(obj_ext) obj/polyweb_0$(obj_ext) obj/server_0$(obj_ext) obj/string_0$(obj_ext) obj/websocket_1$(obj_ext) obj/error_1$(obj_ext) obj/polynet_0$(obj_ext) obj/secure_sockets_0$(obj_ext)
polyweb-tests$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@$(cpp_compiler) $(objects) $(static_libraries) $(cpp_compilation_flags) $(out_path_flag)$@ $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting polyweb-tests$(out_ext) and obj..."
	@rm -rf polyweb-tests$(out_ext) obj
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting polyweb-tests$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying polyweb-tests$(out_ext) to $(prefix)..."
	@cp polyweb-tests$(out_ext) $(prefix)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying polyweb-tests$(out_ext) to $(prefix)!"
.PHONY: install
