# This file was auto-generated by Polybuild

ifndef MODE
	MODE := release
	export MODE
endif

ifndef OS
	OS := $(shell uname)
	export OS
endif

ifeq ($(OS),Windows_NT)
	CC := cl
	CXX := cl
	CL := /nologo
	LINK := /nologo
	MSYS_NO_PATHCONV := 1
	export CC CXX CL MSYS_NO_PATHCONV
endif

all:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory
.PHONY: all

clean:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: clean

install:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: install
